### ISSUE TITLE
Add rate limit

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-cache#1]
Add rate limiting to avoid abuse of the API.

**Comment by mjovanc** [comment]
Good alternative: https://www.npmjs.com/package/express-rate-limit ?

**Comment by Swepool** [comment]
Probably a good idea, checking out the package

**Comment by mjovanc** [comment]
Since there doesn't seem to be any way to relate issues towards one another. This issue relates to: https://github.com/kryptokrona/hugin-cache/issues/26 since we have to take the load/stress testing in consideration when we implement this. 

Perhaps deactivate rate limiting when running the load/stress tests?

**Comment by mjovanc** [comment]
Now implemented.
