### ISSUE TITLE
[Feature]: Get avatar string URL in message object and save to DB

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-cache#168]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by f-r00t** [comment]
Not sure what the purpose of this is. The avatars are generated from the senders XKR-adress, and are easily generated on the frontend. IMO thats where all the avatar handling should occur.

**Comment by mjovanc** [comment]
@f-r00t Perhaps @Swepool can elaborate on this since it was requested by him.

**Comment by Swepool** [comment]
Yes, I had them generated for each address but google slaughter our page score for that. Hence why I thought it could be a good idea to serve the src url instead. One could render this on server side on request or load as few avatars as possible to use pagination to load the rest. Bu tI don't see an issue pre generating them.

**Comment by Swepool** [comment]
For SPA's or apps this is not an issue really.

**Comment by Swepool** [comment]
Would be nice to just src={message.avatar} that shit as well :P

**Comment by f-r00t** [comment]
I see, _thanks Google.._ Well, maybe it's a good idea then!
