### ISSUE TITLE
[Bug]: Unexpected token K in JSON at position 0 on WebSocket stream

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-cache#177]
### What happened?

Ask Swepool.

### Version

1.0.0 (Default)

### On what OS are you experience the problem on?

Mac OS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Swepool** [comment]
To keep the browser connection alive one would have to use `websocket.send()` using an interval for example. This message then gets broadcasted to all connected clients, who would need to handle the incoming data. In this case a client sent "**K**eep me alive" resulting in `Unexpected token K in JSON at position 0`. Now this only applies to browser clients as node env can use `websocket.ping()`.

Fix:
Handle the incoming data correctly or somehow handle sessionID's on server to only send to one user (If this is even possible with websocket)
