### ISSUE TITLE
[Feature]: Change lifetime of websocket to last longer

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-cache#178]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Swepool** [comment]
I know nothing about java, but I heard @TechyGuy17 is pro.

**Comment by TechyGuy17** [comment]
> I know nothing about java, but I heard @TechyGuy17 is pro.

Hold up

**Comment by Swepool** [comment]
Just to add to it, the implementation is correct, we don't need to change the lifetime really. Just add a guard against ping messages so they don't get broadcasted.
