### ISSUE TITLE
Remove frontpage

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-cache#22]
We don't need the frontend. All the API endpoints is much better suited to be viewed/tested on our Postman account. And since people are going to use this and host it, it just feels unnecessary.

**Comment by Swepool** [comment]
Agreed :) Someone can take on the task of building a frontend if needed. Let's focus on the important stuff :D

**Comment by mjovanc** [comment]
Removed implementation. Now currently in dev branch.
