### ISSUE TITLE
Sync data between Hugin Cache apps

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-cache#29]
Sync data between Hugin Cache databases currently running to avoid mismatch of stored data.

**Comment by f-r00t** [comment]
Syncing data between Hugin Caches isn't necessary, or even desirable at times. For monetary transactions on the XKR network sync between nodes is absolutely imperative, but Hugin Cache should work as a sort of "answering machine" for Hugin Messenger. With Munin implemented, messages will be stored in the XKR network mempool for a week (a timespan which may be subject to change). After that messages will be purged from the XKR network, and hopefully the recipient has received the message by then. If that person has not, however, that message is lost forever, unbeknownst to the sender. That's where Hugin Cache should come in as a "backup" that may store messages longer than that, but not necessarily forever. My idea with Hugin Cache is that it may be configured to store message for two weeks, maybe a month, maybe a year - or forever. You may want a personal Hugin Cache that only stores messages addressed to yourself. This means that each Hugin Cache may contain very different information. Hugin Messenger doesn't require concensus between all Hugin Caches, or Hugin Users - only between the specific user's who are communicating with each other.

**Comment by mjovanc** [comment]
Closing this issue. Won't fix.
